### ISSUE TITLE
Visualization not found on server

### ISSUE THREAD

**Issue by Kielland** [miclae76/trellis-chart#3]
Hi

This looks great. But after uploading to Qlik Sense server, when I drag the Trellis Chart icon into an empty sheet, I get the message "Invalid visualization. The visualization was not found on the server: trellis-chart. 

Thanks!
Tor

![bilde1](https://cloud.githubusercontent.com/assets/15069116/14851535/dabb66a2-0c80-11e6-831a-3b588acf96d1.png)

**Comment by miclae76** [comment]
This is a dependency issue I haven't yet solve. dimple js require d3.v3.min but the only way I succeed to get the dependcy is refering the d3 js from their website. So if your server has no access to the web you get this message. I let you know where this is ok.

**Comment by Kielland** [comment]
Thanks for this very swift reply, Michael! My server actually has web access. If I understand you correctly, it will not help me to place d3.v3.min in the program folder?

**Comment by miclae76** [comment]
I just commit changes with local dependency to d3 instead of URL. It works great at my side. If not at yours, tell me what's displayed in the developer console.  I added also my sample app.
KR
Michael

**Comment by Kielland** [comment]
Works like a charm now :-)
Thanks a lot!
Tor
